id: P891E64CD
initial_creation_type: input
source_metadata:
  title: Dharmak카rti Series
  language: en
  description: 'Texts by and about the celebrated Indian philosopher Dharmak카rti (chos
    kyi grags pa):'
  volume:
    6bca86bcc112461ea6fda5ad68e6160b:
      title: Guru S훮dhana of Glorious Dharmak카rti
      parent: Guru Yoga
created_at: '2022-03-01T02:14:55.812127'
last_modified_at: '2022-03-01T02:14:55.812132'
